seed: 42

paths:
  raw: data/raw
  proc: data/processed
  splits: data/processed/splits
  images: data/processed/images
  vqa: data/processed/vqa

data:
  image_size: 224
  classes: ["akiec","bcc","bkl","df","mel","nv","vasc"]

augment:            
  rotation_deg: 10   
  translate: 0.05  
  brightness: 0.05   
  hflip: true       

baseline:
  model: "resnet18"                   
  batch_size: 32
  epochs: 20
  lr: 5e-4

class_weighting:
  enabled: true
  cap: 3.0

vqa:
  question_template: "Classify this skin lesion. Answer with only one label: akiec, bcc, bkl, df, mel, nv, or vasc."
  out_dir: data/processed/vqa_prompt5

vlm:
  model_id: "microsoft/llava-med-v1.5-mistral-7b"
  max_new_tokens: 8
  temperature: 0.0
  device_map: "auto"     
  dtype: "auto" 

lava_repo_path: /home/alaa.mohamed/Lab6/LLaVA-Med/